---
- name: Migrate from OpenShift SDN to OVN-Kubernetes
  hosts: localhost
  gather_facts: no
  roles:
    - role: migration
      vars:
        co_timeout: 1200
        clean_migration_timeout: 120
        change_migration_timeout: 120
        target_network_type: OVNKubernetes
        mco_update_timeout: 300s
        mcp_completion_timeout: 2700  # Timeout in seconds
        ovn_network_type: OVNKubernetes
        ovn_co_timeout: 120  # Timeout in seconds
        ovn_multus_timeout: 300  # Timeout in seconds for waiting for Multus pods
        verify_machine_config_timeout: 300
        network_type: OVNKubernetes
        conflicting_cidr_ranges:
          - "100.64.0.0/16"
          - "169.254.169.0/29"
          - "100.88.0.0/16"
          - "fd98::/64"
          - "fd69::/125"
          - "fd97::/64"