---
- name: End-to-End Test for wait_for_network_co Module (Real OpenShift)
  hosts: localhost
  gather_facts: no
  vars:
    ovn_co_timeout: 120  # Set a reasonable timeout for the test
  tasks:

    - name: Run wait_for_network_co module (Success scenario)
      wait_for_network_co:
        timeout: "{{ ovn_co_timeout }}"
      register: result_success

    - name: Debug module output (Success)
      debug:
        var: result_success

    - name: Assert success scenario
      assert:
        that:
          - result_success is success
          - '"Network Cluster Operator is in PROGRESSING=True state." in result_success.msg'
      when: result_success is success

    - name: Run wait_for_network_co module (Failure due to timeout)
      wait_for_network_co:
        timeout: 1  # Force an immediate timeout
      register: result_timeout
      ignore_errors: yes

    - name: Debug module output (Timeout Failure)
      debug:
        var: result_timeout

    - name: Assert failure due to timeout
      assert:
        that:
          - result_timeout is failed
          - '"Timeout waiting for Network Cluster Operator to reach PROGRESSING=True." in result_timeout.msg'
      when: result_timeout is failed
